// Code generated from Cetas models.js. DO NOT EDIT.

package catalog

var generated = []Model{
	{ID: "deepseek-chat", Label: "DeepSeek V3.2", Editeur: "deepseek", InputPer1M: 0.14, OutputPer1M: 0.28},
	{ID: "deepseek-flash", Label: "DeepSeek Flash", Editeur: "deepseek", InputPer1M: 0.15, OutputPer1M: 0.6},
	{ID: "deepseek-v4-pro", Label: "DeepSeek V4 Pro", Editeur: "deepseek", InputPer1M: 0.66, OutputPer1M: 1.98},
	{ID: "big-pickle-zen", Label: "Big Pickle", Editeur: "opencode", InputPer1M: 0.0, OutputPer1M: 0.0},
	{ID: "ling-3.0-flash-fin-free-zen", Label: "Ling 3.0 Flash Fin Free", Editeur: "opencode", InputPer1M: 0.0, OutputPer1M: 0.0},
	{ID: "mimo-v2.5-free-zen", Label: "MiMo V2.5 Free", Editeur: "opencode", InputPer1M: 0.0, OutputPer1M: 0.0},
	{ID: "nemotron-3-ultra-free-zen", Label: "Nemotron 3 Ultra Free", Editeur: "opencode", InputPer1M: 0.0, OutputPer1M: 0.0},
	{ID: "nemotron-3.5-lightning-free-zen", Label: "Nemotron 3.5 Lightning Free", Editeur: "opencode", InputPer1M: 0.0, OutputPer1M: 0.0},
	{ID: "gpt-5.6-luna-zen", Label: "GPT 5.6 Luna", Editeur: "opencode", InputPer1M: 0.2, OutputPer1M: 1.2},
	{ID: "minimax-m3-zen", Label: "MiniMax M3", Editeur: "opencode", InputPer1M: 0.3, OutputPer1M: 1.2},
	{ID: "qwen3.5-plus-zen", Label: "Qwen3.5 Plus", Editeur: "opencode", InputPer1M: 0.2, OutputPer1M: 1.2},
	{ID: "gpt-5.4-nano-zen", Label: "GPT 5.4 Nano", Editeur: "opencode", InputPer1M: 0.2, OutputPer1M: 1.25},
	{ID: "qwen3.7-plus-zen", Label: "Qwen3.7 Plus", Editeur: "opencode", InputPer1M: 0.4, OutputPer1M: 1.6},
	{ID: "qwen3.6-plus-zen", Label: "Qwen3.6 Plus", Editeur: "opencode", InputPer1M: 0.5, OutputPer1M: 3.0},
	{ID: "glm-5-zen", Label: "GLM 5", Editeur: "opencode", InputPer1M: 1.0, OutputPer1M: 3.2},
	{ID: "mimo-v2.5-go", Label: "MiMo V2.5", Editeur: "opencode-go", InputPer1M: 0.14, OutputPer1M: 0.28},
	{ID: "glm-5.3-flash-go", Label: "GLM-5.3 Flash", Editeur: "opencode-go", InputPer1M: 0.15, OutputPer1M: 0.5},
	{ID: "hy3-go", Label: "Hy3", Editeur: "opencode-go", InputPer1M: 0.14, OutputPer1M: 0.58},
	{ID: "gpt-5.6-luna-go", Label: "GPT 5.6 Luna", Editeur: "opencode-go", InputPer1M: 0.2, OutputPer1M: 1.2},
	{ID: "longcat-2.0-go", Label: "LongCat 2.0", Editeur: "opencode-go", InputPer1M: 0.3, OutputPer1M: 1.2},
	{ID: "minimax-m3-go", Label: "MiniMax M3", Editeur: "opencode-go", InputPer1M: 0.3, OutputPer1M: 1.2},
	{ID: "qwen3.7-plus-go", Label: "Qwen3.7 Plus", Editeur: "opencode-go", InputPer1M: 0.4, OutputPer1M: 1.6},
	{ID: "qwen3.6-plus-go", Label: "Qwen3.6 Plus", Editeur: "opencode-go", InputPer1M: 0.5, OutputPer1M: 3.0},
	{ID: "poolside/laguna-xs-2.1", Label: "Laguna XS 2.1", Editeur: "openrouter", InputPer1M: 0.06, OutputPer1M: 0.12},
	{ID: "qwen/qwen3.7-flash", Label: "Qwen3.7 Flash", Editeur: "openrouter", InputPer1M: 0.03, OutputPer1M: 0.13},
	{ID: "poolside/laguna-s-2.1", Label: "Laguna S 2.1", Editeur: "openrouter", InputPer1M: 0.09, OutputPer1M: 0.18},
	{ID: "qwen/qwen3-30b-a3b-instruct-2507", Label: "Qwen3 30B A3B", Editeur: "openrouter", InputPer1M: 0.05, OutputPer1M: 0.19},
	{ID: "z-ai/glm-5.3-flash", Label: "GLM 5.3 Flash", Editeur: "openrouter", InputPer1M: 0.07, OutputPer1M: 0.25},
	{ID: "z-ai/glm-5.3-flash-2", Label: "GLM 5.3 Flash", Editeur: "openrouter", InputPer1M: 0.07, OutputPer1M: 0.25},
	{ID: "qwen/qwen3.5-flash-02-23", Label: "Qwen3.5-Flash", Editeur: "openrouter", InputPer1M: 0.07, OutputPer1M: 0.26},
	{ID: "deepseek/deepseek-v4-flash-0731", Label: "V4 Flash 0731", Editeur: "openrouter", InputPer1M: 0.14, OutputPer1M: 0.28},
	{ID: "xiaomi/mimo-v2.5", Label: "MiMo-V2.5", Editeur: "openrouter", InputPer1M: 0.14, OutputPer1M: 0.28},
	{ID: "google/gemini-2.5-flash-lite", Label: "Gemini 2.5 Flash Lite", Editeur: "openrouter", InputPer1M: 0.1, OutputPer1M: 0.4},
	{ID: "tencent/hy3", Label: "Hy3", Editeur: "openrouter", InputPer1M: 0.13, OutputPer1M: 0.53},
	{ID: "mistralai/mistral-small-2603", Label: "Mistral Small 4", Editeur: "openrouter", InputPer1M: 0.15, OutputPer1M: 0.6},
	{ID: "tencent/hy3-preview", Label: "Hy3 preview", Editeur: "openrouter", InputPer1M: 0.18, OutputPer1M: 0.6},
	{ID: "meta-llama/llama-4-maverick", Label: "Llama 4 Maverick", Editeur: "openrouter", InputPer1M: 0.2, OutputPer1M: 0.7},
	{ID: "qwen/qwen3-coder-next", Label: "Qwen3 Coder Next", Editeur: "openrouter", InputPer1M: 0.12, OutputPer1M: 0.8},
	{ID: "xiaomi/mimo-v2.5-pro", Label: "MiMo-V2.5-Pro", Editeur: "openrouter", InputPer1M: 0.43, OutputPer1M: 0.87},
	{ID: "mistralai/codestral-2508", Label: "Codestral 2508", Editeur: "openrouter", InputPer1M: 0.3, OutputPer1M: 0.9},
	{ID: "qwen/qwen3.6-35b-a3b", Label: "Qwen3.6 35B A3B", Editeur: "openrouter", InputPer1M: 0.1, OutputPer1M: 0.9},
	{ID: "qwen/qwen3.6-flash", Label: "Qwen3.6 Flash", Editeur: "openrouter", InputPer1M: 0.19, OutputPer1M: 1.12},
	{ID: "stepfun/step-3.7-flash", Label: "Step 3.7 Flash", Editeur: "openrouter", InputPer1M: 0.2, OutputPer1M: 1.15},
	{ID: "kwaipilot/kat-coder-pro-v2", Label: "KAT-Coder-Pro V2", Editeur: "openrouter", InputPer1M: 0.3, OutputPer1M: 1.2},
	{ID: "meituan/longcat-2.0", Label: "LongCat 2.0", Editeur: "openrouter", InputPer1M: 0.3, OutputPer1M: 1.2},
	{ID: "qwen/qwen3.7-plus", Label: "Qwen3.7 Plus", Editeur: "openrouter", InputPer1M: 0.32, OutputPer1M: 1.28},
	{ID: "z-ai/glm-5", Label: "GLM 5", Editeur: "openrouter", InputPer1M: 0.6, OutputPer1M: 1.92},
	{ID: "z-ai/glm-5-or", Label: "GLM 5", Editeur: "openrouter", InputPer1M: 0.6, OutputPer1M: 1.92},
	{ID: "qwen/qwen3.6-plus", Label: "Qwen3.6 Plus", Editeur: "openrouter", InputPer1M: 0.33, OutputPer1M: 1.95},
	{ID: "google/gemini-2.5-flash", Label: "Gemini 2.5 Flash", Editeur: "openrouter", InputPer1M: 0.3, OutputPer1M: 2.5},
	{ID: "anthropic/claude-sonnet-4.5", Label: "Claude Sonnet 4.5", Editeur: "openrouter", InputPer1M: 3.0, OutputPer1M: 15.0},
}
